/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idiomata;

import idiomata.model.User;

import javax.persistence.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        final EntityManagerFactory factory = Persistence.createEntityManagerFactory("idiomata");

        final EntityManager entityManager = factory.createEntityManager();

        final EntityTransaction transaction = entityManager.getTransaction();

        transaction.begin();
        final User messi = new User("lionel", "messi@gmail.com", "Italian");

        entityManager.persist(messi);

        transaction.commit();

        entityManager.close();

    }
}
