/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idiomata;

import idiomata.repository.UserRepository;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        UserRepository repo = new UserRepository();

        repo.createUser("Lionel", "queMiras@gmail.com", "French");

        System.out.println(repo.findUserById(1).getFirstName());
    }
}
